# -*- coding: utf-8 -*-
"""App Matriz ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zU1_ruCkR0kD72GbKt3MZGWlIpEDi_L-
"""

import streamlit as st
import numpy as np


st.image("URC.png", caption="LCFI-URC Universidad Rosario Castellanos", width=200)


# Definir la función ReLU
def relu(z):
    return np.maximum(0, z)

# Definir las operaciones neuronales con tres capas
def forward_pass(X, W1, b1, W2, b2, W3, b3):
    # Cálculo de Z1
    Z1 = np.dot(X, W1) + b1
    # Aplicar ReLU en Z1 para obtener A1
    A1 = relu(Z1)

    # Cálculo de Z2
    Z2 = np.dot(A1, W2) + b2
    # Aplicar ReLU en Z2 para obtener A2
    A2 = relu(Z2)

    # Cálculo de Z3
    Z3 = np.dot(A2, W3) + b3
    # Salida final
    Y_hat = Z3  # Aquí puedes usar otra función de activación si es necesario

    return Z1, A1, Z2, A2, Z3, Y_hat

# Configurar la aplicación Streamlit
st.title('Red Neuronal Simple con Streamlit (Tres Capas)')

st.header('Parámetros de Entrada')

# Entradas para la matriz X
st.subheader('Matriz de Entrada X')
x_rows = st.number_input('Número de filas de X', min_value=1, max_value=10, value=3)
x_cols = st.number_input('Número de columnas de X (dimensión de W1)', min_value=1, max_value=10, value=3)

# Generar matriz X
X = []
for i in range(x_rows):
    row = st.text_input(f'Fila {i+1} de X (separar valores por comas)', value='0,0,0')
    X.append([float(val) for val in row.split(',')])

X = np.array(X)

# Definir pesos y sesgos (fijos para la demostración)
W1 = np.array([[0.2, 0.4], [0.5, 0.6], [0.1, 0.3]])  # Cambia esto según tus necesidades
b1 = np.array([[0.1, 0.2]])  # Cambia esto según tus necesidades
W2 = np.array([[0.3], [0.7]])  # Cambia esto según tus necesidades
b2 = np.array([[0.5]])  # Cambia esto según tus necesidades
W3 = np.array([[0.6]])  # Cambia esto según tus necesidades
b3 = np.array([[0.4]])  # Cambia esto según tus necesidades

# Realizar el forward pass y mostrar resultados
if st.button('Calcular'):
    Z1, A1, Z2, A2, Z3, Y_hat = forward_pass(X, W1, b1, W2, b2, W3, b3)

    st.subheader('Resultados:')
    st.write('Z1:', Z1)
    st.write('A1 (ReLU(Z1)):', A1)
    st.write('Z2:', Z2)
    st.write('A2 (ReLU(Z2)):', A2)
    st.write('Z3:', Z3)
    st.write('Y_hat (Salida Final):', Y_hat)


# Insertar el código HTML con estilos personalizados
st.markdown("""
    <div class="container col-sm-5 creditos text-center">
        <p style="margin-top:0;margin-bottom:0;font-size:15px;color: #dad3d5;text-align:center">
            <strong>Colaboración:</strong>
        </p>
        <p style="margin-top:0;margin-bottom:0;font-size:12px;color: #dad3d5;text-align:center">
            <strong>Asignatura (UCA): Métodos Cuantitativos  LCFI-URC</strong>
        </p>
        <p style="margin-top:0;margin-bottom:0;font-size:12px;color: #dad3d5;text-align:center">
            <strong>Grupo 103 GAM-LCFI-URC</strong>
        </p>
    </div>
""", unsafe_allow_html=True)